// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szyjbnhqxxgyzcdbeorx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6eWpibmhxeHhneXpjZGJlb3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNjIxMzYsImV4cCI6MjA2ODYzODEzNn0.yDg9UDhRm0RiHzdPGh0N4fk4D013lFmdD12xtF_f5pQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});